playlist_name = 'Office Vibes: Cheerful & Energetic'
playlist_description = 'Una selezione di brani allegri e energici per mantenere la produttività e il buon umore in ufficio.'
playlist_public = False
tracks_to_search = [
    'Electric Fel MGMT',
    'Time too Pretend MGMT',
    'Kids - MGMT',
    'Dog Days Are Over Florence + The Machine',
    'Float On Modest Mouse',
    'Pumped Up Kicks Foster the People',
    '1901 Phoenix',
    'Tongue Tied Grouplove',
    'Sleepyhead Passion Pit',
    'Little Secrets Passion Pit',
    'Anna Sun WALK THE MOON',
    'San Francisco The Mowgli\'s',
    'Good Old Days Macklemore feat. Kesha',
    'Take a Walk Passion Pit',
    'Feel It Still Portugal. The Man',
    'Riptide Vance Joy',
    'Adventure of a Lifetime Coldplay',
    'Home Edward Sharpe & The Magnetic Zeros',
    'On Top of the World Imagine Dragons',
    'Best Day of My Life American Authors',
    'Shut Up and Dance WALK THE MOON',
    'Lisztomania Phoenix',
    'Holiday Vampire Weekend',
    'Unbelievers Vampire Weekend',
    'Spirits The Strumbellas',
    'Dreaming Smallpools',
    'Geronimo Sheppard',
    'Mountain Sound Of Monsters and Men',
    'First Day of My Life Bright Eyes',
    'Dreams Beck',
    'Island in the Sun Weezer',
    'Walking on a Dream Empire of the Sun',
    'Alive Empire of the Sun',
    'Sweet Disposition The Temper Trap',
    'Safe and Sound Capital Cities',
    'Harlem New Politics',
    'Come On Eileen Dexys Midnight Runners',
    'Walking on Sunshine Katrina and the Waves',
    'Good Times Roll The Cars',
    'Dancing in the Moonlight King Harvest',
    'Brandy (You\'re a Fine Girl) Looking Glass',
    'Mr. Blue Sky Electric Light Orchestra',
    'September Earth, Wind & Fire',
    'Take It Easy Eagles',
    'Go Your Own Way Fleetwood Mac',
    'Dreams Fleetwood Mac',
    'Africa Toto',
    'Everybody Wants to Rule the World Tears for Fears',
    'You Make My Dreams Daryl Hall & John Oates',
    'Here Comes the Sun The Beatles',
    'Wouldn\'t It Be Nice The Beach Boys',
    'Uptown Girl Billy Joel',
    'Jack and Diane John Mellencamp',
    'I\'m Still Standing Elton John',
    'Dancing in the Dark Bruce Springsteen',
    'Free Fallin\' Tom Petty',
    'American Girl Tom Petty and the Heartbreakers',
    'Rebel Rebel David Bowie',
    'Heroes David Bowie'
]
